export enum UsuarioEstado {
  ACTIVO = 'ACTIVO',
  INACTIVO = 'INACTIVO',
  PENDIENTE_ASIGNACION_ROL = 'PENDIENTE_ASIGNACION_ROL',
  PENDIENTE_VERIFICACION = 'PENDIENTE_VERIFICACION',
  EXPIRADO = 'EXPIRADO',
}
